Python script to generate tabby file table from directory
psychoinformatics-de/datalad-tabby pull request #60
Opened 2023-07-13 09:50 UTC by jsheunis

This is in response to https://github.com/psychoinformatics-de/datalad-tabby/issues/33

In the issue we haven't yet resolved what form the solution would take, but I wanted to get something done so I decided to provide a pure Python script that prints a table with information about the files contained in a directory on a filesystem. File information includes: file path, file content checksum (using a specified hash algorithm), and file size in bytes. The table can be output to stdout or to a text file in TSV format. The script can also recurse into subdirectories.

Possible other useful additional arguments: levels of recursion, file exclusion regex.

In order to make this executable on multiple OSs without requiring Python installation, we could consider pyinstaller and running a github action or appveyor workflow to generate executables for the different operating systems.

2023-07-27 11:20 UTC, mih requested changes
Thx, this works for me!

I would suggest to make the following changes.

- Move it out of the package source tree. it is a standalone script that could be downloaded individually (which is the main benefit, because package installation pull in datalad, but see #95(. I suggest `tools/dir2filetable.py`.
- add a header row. This is needed to be compliant with the `many` table layout. If this is added, we may need to rethink the default for `--recursive`. I'd set it to `True` to get the full table -- as ooposed to suggesting to build many table and merge them. This may indicate that added a column header should be optional (and likely enabled by default).
- consider adopting/aligning with the `tby-ds1` convention (see #101), which would specify the column headers and semantics
- if `tby-ds1` is adopted, consider writing the content out into a file with the correct name `<prefix>[/_]files@tby-ds1.tsv`

2023-07-27 11:26 UTC, jsheunis commented
Thanks for the useful feedback 👍

2023-07-27 13:05 UTC, jsheunis commented
> add a header row. This is needed to be compliant with the many table layout. If this is added, we may need to rethink the default for --recursive. I'd set it to True to get the full table -- as ooposed to suggesting to build many table and merge them. This may indicate that added a column header should be optional (and likely enabled by default).

TBC: the header is already added to the file output, just not to the stdout (yet). The header will be changed to be compliant with `@tby-ds1` convention. But I don't see how adding a header has influence on the recursive process, since adding the header is done once at the output stage, after all possible recursion or non-recursion has been completed.

Regarding doing recursion by default, that seems sensible. The options IMO would then either be:
- change the current flag to something like `--no-recursion` with `action=store_false` (default `False`), or
- change the current flag to `--recursion-level` an integer which defaults to infinity
Any preference or alternatives?

2023-07-27 21:09 UTC, jsheunis commented on tools/dir2filetable.py
> +            shoult be printed.
```suggestion
            should be printed.
```

2023-07-28 14:24 UTC, mih requested changes
Thanks, looks good. I made a series of suggested to keep the not/non recursion business a CLI problem.

2023-07-28 14:24 UTC, mih commented on tools/dir2filetable.py
> +    nonrecursive: bool = False,
```suggestion
    recursive: bool = True,
```

2023-07-28 14:24 UTC, mih commented on tools/dir2filetable.py
> +    _dir2filelist(Path(rootpath), Path(rootpath), out_info, hash, not nonrecursive)
```suggestion
    _dir2filelist(Path(rootpath), Path(rootpath), out_info, hash, recursive)
```

2023-07-28 14:24 UTC, mih commented on tools/dir2filetable.py
> +        nonrecursive=args.non_recursive,
```suggestion
        recursive=not args.non_recursive,
```

2023-07-28 14:29 UTC, mih approved these changes

2023-07-28 14:29 UTC, merged